### ISSUE TITLE
isue piece promoting

### ISSUE THREAD

**Issue by gilberto85** [Stermere/Checkers-Engine#6]
if this is american checkers rules, when a pice is promoted to a king, then after its promoted it should pass the turn to the oponent , can you make it stronger, maybe for a novice person this is hard but not for an experienced person

**Comment by gilberto85** [comment]
btw nice job on the coding

**Comment by Stermere** [comment]
Thanks for bringing that up I have fixed it on the main branch and will update the website soon. As for the playing strength, I do plan to improve the evaluation with neural nets, however, if you were playing on the website its strength is bottlenecked by the hardware of the free hosting service I have it running on.

**Comment by gilberto85** [comment]
Nice, with learning reinforcement it will be much efficient i can help to train the Ai if you want to

**Comment by Stermere** [comment]
Thanks for the offer, I've been working on training a model in PyTorch
already that I plan to convert to an ONNX model for use by the engine. I
will have it committed to the repository soon if you are interested

**Comment by gilberto85** [comment]
i am really interested please update the page so i can play with it

**Comment by Stermere** [comment]
Forgot to update it. The promotion fix is now on the site along with giving it 1 second to think instead of 0.25 seconds on the hardest difficulty.

**Comment by gilberto85** [comment]
oh so is updated now ?

**Comment by gilberto85** [comment]
how can you add more difficulty to the game ?

**Comment by Stermere** [comment]
The 4 buttons below the board labeled easy, medium, hard, and master change the difficulty, and yes it is updated.

**Comment by gilberto85** [comment]
The only reason why am asking hiw can we add more difficulty is because I
already bet on the hardest level

**Comment by Stermere** [comment]
You have to set up the codebase locally, then and then you can set the thinking time to whatever you want.
